const express=require('express')
var cors=require('cors')
const fileUpload = require('express-fileupload');
const userrouter=require('./routes/user')
const jobrouter=require('./routes/job')
const dashbordrouter=require('./routes/dashbordadmin')
const dashborduser=require('./routes/dashborduser')
const dashbordrecreteur=require('./routes/dashbordrecreteur')
const path =require('path')
var app =express()
app.use(cors())
app.use(fileUpload())
app.use(express.urlencoded({extended:true}))
app.use(express.json())
app.use('/user',userrouter)
app.use('/jobs',jobrouter)
app.use('/dashbord',dashbordrouter)
app.use('/dashbordadmin',dashbordrouter)
app.use('/dashbordrecreteur',dashbordrecreteur)
app.use('/dashborduser',dashborduser)
app.use(express.json())
app.use(express.static("./public"))

module.exports=app